name: "Stremio Server for Home Assistant"
description: "Runs a local Stremio server accessible via an IP port"
version: "0.1.2-beta"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  11470/http: 11470
  12470/https: 12470